### ISSUE TITLE
Definir categorias

### ISSUE THREAD

**Issue by p1nh0** [Sonoscopia/Transarkiv#11]
Exemplo: Ambient, Rhythmic, etc...

(julgo que deverá ser o Gustavo a fazer isto uma vez que tem melhor noção dos conteúdos do arquivo)

**Comment by rdias74** [comment]
sim, concordo. Acho que ele já tem uma ideia para as categorias.

**Comment by rdias74** [comment]
@p1nh0 ,  Sugiro para já apenas 4 categorias: Ambient, Rhythmic, Detail, Voice.

**Comment by p1nh0** [comment]
ok...já estou a fazer upload para o servidor FTP

está em ~/Transarkiv/
depois tem as 4 pastas: 01_Ambient, 02_Rhythmic, 03_Detail, 04_Voice
os ficheiros estão numerados c/ 4 dígitos no início (ex: 0001 Frogs_CUT1.mp3)

**Comment by p1nh0** [comment]
- Field Recordings
- Ambient (and drones) 
- Textural 
- Rhythmic
- Melodic
- Performances
