### ISSUE TITLE
Limitar o número de players

### ISSUE THREAD

**Issue by p1nh0** [Sonoscopia/Transarkiv#17]
Temos que colocar um limite no número de players...
@rdias74 qual deverá ser o limite máximo: 10, 15, 20 ?

Eu penso que dez deverá ser suficiente... ou melhor ainda um múltiplo das categorias existentes: por exemplo se existirem 6 categorias poderíamos deixar um limite de 12 players.

**Comment by rdias74** [comment]
Olá. Na prática talvez seja demais porque pode ser confusão a mais.
Quando fizeres a ligação ao banco de sons experimenta e faz como te parecer melhor.

**Comment by p1nh0** [comment]
pr'agora limitei a 12 Players
depois é fácil mudar
é só alterar a variável 'maxPlayers' em global.js
