### ISSUE TITLE
Move filter parameters

### ISSUE THREAD

**Issue by p1nh0** [Sonoscopia/Transarkiv#43]
Move filter parameters automatically

**Comment by p1nh0** [comment]
@rdias74 achas que o movimento automático do filtro devia ser feito no AutoMove ou no AutoPlay ?

**Comment by rdias74** [comment]
@p1nh0  boa pergunta... provavelmente no autoplay

**Comment by p1nh0** [comment]
depois de discutir esta feature com a malta da Sonoscopia chegou-se à conclusão que é melhor não a desenvolver uma vez que iria resultar num efeito de sweep enfadonho e constante...

**Comment by rdias74** [comment]
Olá
Isso depende muito do tipo de movimento que for implementado. Não precisa nem seria para ser enfadonho nem constante...
De qualquer forma, concordo que não é nada prioritário e que pode ser implementado mais tarde, se virmos que pode valer a pena (que pode não ser o caso).

abraço
